import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Node.js 내장 모듈은 Electron에서 사용 가능하므로 external로 유지
    // 단, express 등에서 사용하는 모듈은 제외
  ],
  platform: "node",  // Node.js 내장 모듈 resolve
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? "external" : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: false,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
